### PR TITLE
google

### PR DESCRIPTION
**Pull request by chuanchyone1**

### CODE REVIEW

**Review by JuanDelahozMiranda — CHANGES_REQUESTED** [review]
Hi Juan, remember fix the EOF in google.cy.js file. (delete the spaces to the end)

**Comment by chuanchyone1** [comment]
@JuanDelahozMiranda  Changes made

**Review by danielgalvis98 — COMMENTED** [review]
Please add a screenshot showing that the test was executed succesfully

**Comment by chuanchyone1** [comment]
> Please add a screenshot showing that the test was executed succesfully

image

**Review by danielgalvis98 — APPROVED** [review]

**Review by JuanDelahozMiranda — APPROVED** [review]

**Pull request merged**
